"""Ensemble strategy that combines predictions from multiple sub-strategies.

Computes weighted-average probability distributions across strategies, then
generates multiple candidate predictions from the combined distribution.
"""

from __future__ import annotations

import itertools
import math
from dataclasses import dataclass, field

from app.models.draw import Draw
from app.strategies.base import BaseStrategy, PredictionResult


@dataclass
class StrategyWeight:
    """Pairs a strategy instance with its combination weight."""

    strategy: BaseStrategy
    weight: float = 1.0


class EnsembleStrategy(BaseStrategy):
    """Weighted combination of multiple prediction strategies.

    For each digit position the ensemble computes a weighted average of the
    per-strategy probability distributions, then selects the most likely
    digits.  Multiple candidate predictions are generated by considering the
    top-k digits at each position.
    """

    name: str = "ensemble"

    def __init__(
        self,
        strategy_weights: list[StrategyWeight] | None = None,
        top_k_per_position: int = 3,
        max_candidates: int = 5,
    ) -> None:
        self.strategy_weights: list[StrategyWeight] = strategy_weights or []
        self.top_k_per_position = top_k_per_position
        self.max_candidates = max_candidates

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def predict(
        self,
        game_type: str,
        draw_time: str,
        history: list[Draw],
    ) -> list[PredictionResult]:
        if not self.strategy_weights:
            return []

        num_positions = self.get_digit_count(game_type)

        # Collect predictions from each sub-strategy.
        all_results: list[tuple[PredictionResult, float]] = []
        for sw in self.strategy_weights:
            preds = sw.strategy.predict(game_type, draw_time, history)
            if preds:
                # Use only the best prediction from each strategy.
                all_results.append((preds[0], sw.weight))

        if not all_results:
            return []

        # Build the combined probability distribution.
        combined_probs = self._combine_distributions(all_results, num_positions)

        # Generate candidate predictions from the combined distribution.
        candidates = self._generate_candidates(combined_probs, num_positions)
        return candidates

    def train(self, game_type: str, history: list[Draw]) -> None:
        """Delegate training to each sub-strategy."""
        for sw in self.strategy_weights:
            sw.strategy.train(game_type, history)

    def set_weights(self, weights: dict[str, float]) -> None:
        """Update weights by strategy name."""
        for sw in self.strategy_weights:
            if sw.strategy.name in weights:
                sw.weight = weights[sw.strategy.name]

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _combine_distributions(
        results_with_weights: list[tuple[PredictionResult, float]],
        num_positions: int,
    ) -> list[list[float]]:
        """Weighted average of digit probability distributions.

        Returns a list of ``num_positions`` distributions, each with 10 floats
        that sum to 1.0.
        """
        total_weight = sum(w for _, w in results_with_weights)
        if total_weight <= 0:
            total_weight = 1.0

        combined: list[list[float]] = [[0.0] * 10 for _ in range(num_positions)]

        for result, weight in results_with_weights:
            norm_w = weight / total_weight
            for pos in range(num_positions):
                if pos < len(result.digit_probabilities):
                    for d in range(10):
                        combined[pos][d] += result.digit_probabilities[pos][d] * norm_w

        # Renormalize each position to ensure they sum to exactly 1.0.
        for pos in range(num_positions):
            pos_sum = sum(combined[pos])
            if pos_sum > 0:
                combined[pos] = [p / pos_sum for p in combined[pos]]
            else:
                # Fallback: uniform distribution.
                combined[pos] = [0.1] * 10

        return combined

    def _generate_candidates(
        self,
        combined_probs: list[list[float]],
        num_positions: int,
    ) -> list[PredictionResult]:
        """Generate top candidate predictions from the combined distribution.

        Uses the top-k digits at each position and scores all combinations,
        returning up to ``self.max_candidates`` predictions sorted by
        descending confidence.
        """
        # For each position, get top-k digits sorted by probability desc.
        top_k_digits: list[list[int]] = []
        for pos in range(num_positions):
            ranked = sorted(range(10), key=lambda d, p=pos: combined_probs[p][d], reverse=True)
            top_k_digits.append(ranked[: self.top_k_per_position])

        # Generate all combinations of top-k digits across positions.
        all_combos = list(itertools.product(*top_k_digits))

        # Score each combination.
        scored: list[tuple[list[int], float, float]] = []
        for combo in all_combos:
            digits = list(combo)
            # Joint probability is the product of per-position probabilities.
            joint_prob = 1.0
            for pos, d in enumerate(digits):
                joint_prob *= combined_probs[pos][d]
            confidence = self._entropy_based_confidence(combined_probs)
            scored.append((digits, confidence, joint_prob))

        # Sort by joint probability descending.
        scored.sort(key=lambda x: x[2], reverse=True)

        candidates: list[PredictionResult] = []
        for digits, confidence, joint_prob in scored[: self.max_candidates]:
            candidates.append(
                PredictionResult(
                    digits=digits,
                    confidence=confidence,
                    digit_probabilities=combined_probs,
                    metadata={
                        "strategy": "ensemble",
                        "joint_probability": joint_prob,
                        "component_strategies": [
                            sw.strategy.name for sw in self.strategy_weights
                        ],
                        "weights": {
                            sw.strategy.name: sw.weight for sw in self.strategy_weights
                        },
                    },
                )
            )

        return candidates

    @staticmethod
    def _entropy_based_confidence(distributions: list[list[float]]) -> float:
        """Confidence = 1 - normalized_entropy, averaged across positions.

        When the distribution is uniform (max entropy), confidence is 0.
        When the distribution has all mass on one digit, confidence is 1.
        """
        max_entropy = math.log(10)  # log(10) for 10-digit uniform
        if max_entropy == 0:
            return 0.0

        position_confidences: list[float] = []
        for probs in distributions:
            entropy = 0.0
            for p in probs:
                if p > 0:
                    entropy -= p * math.log(p)
            normalized = entropy / max_entropy
            position_confidences.append(1.0 - normalized)

        if not position_confidences:
            return 0.0
        return sum(position_confidences) / len(position_confidences)
