"""initial schema

Revision ID: 7e043cec908a
Revises: 
Create Date: 2026-03-16 05:24:19.770746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7e043cec908a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.DateTime(), nullable=False),
    sa.Column('draw_time', sa.String(length=10), nullable=False),
    sa.Column('digit_1', sa.Integer(), nullable=False),
    sa.Column('digit_2', sa.Integer(), nullable=False),
    sa.Column('digit_3', sa.Integer(), nullable=False),
    sa.Column('digit_4', sa.Integer(), nullable=True),
    sa.Column('straight_prize', sa.Float(), nullable=True),
    sa.Column('box_prize', sa.Float(), nullable=True),
    sa.Column('straight_winners', sa.Integer(), nullable=True),
    sa.Column('box_winners', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("draw_time IN ('midday', 'evening')", name='ck_draws_draw_time'),
    sa.CheckConstraint("game_type IN ('daily3', 'daily4')", name='ck_draws_game_type'),
    sa.CheckConstraint('digit_1 BETWEEN 0 AND 9', name='ck_draws_digit_1'),
    sa.CheckConstraint('digit_2 BETWEEN 0 AND 9', name='ck_draws_digit_2'),
    sa.CheckConstraint('digit_3 BETWEEN 0 AND 9', name='ck_draws_digit_3'),
    sa.CheckConstraint('digit_4 IS NULL OR digit_4 BETWEEN 0 AND 9', name='ck_draws_digit_4'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_type', 'draw_number', name='uq_game_draw_number')
    )
    with op.batch_alter_table('draws', schema=None) as batch_op:
        batch_op.create_index('ix_draws_game_date_desc', ['game_type', sa.literal_column('draw_date DESC')], unique=False)
        batch_op.create_index('ix_draws_game_time', ['game_type', 'draw_time'], unique=False)

    op.create_table('model_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('window_type', sa.String(length=10), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('straight_hits', sa.Integer(), nullable=False),
    sa.Column('box_hits', sa.Integer(), nullable=False),
    sa.Column('straight_hit_rate', sa.Float(), nullable=False),
    sa.Column('box_hit_rate', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('calibration_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_performance', schema=None) as batch_op:
        batch_op.create_index('ix_model_perf_strategy_game', ['strategy_name', 'game_type'], unique=False)
        batch_op.create_index('ix_model_perf_window', ['window_type'], unique=False)

    op.create_table('stat_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_stat_snapshots_date', ['snapshot_date'], unique=False)
        batch_op.create_index('ix_stat_snapshots_game_type', ['game_type', 'stat_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_params', sqlite.JSON(), nullable=True),
    sa.Column('start_draw_number', sa.Integer(), nullable=False),
    sa.Column('end_draw_number', sa.Integer(), nullable=False),
    sa.Column('training_window', sa.Integer(), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('straight_hits', sa.Integer(), nullable=False),
    sa.Column('box_hits', sa.Integer(), nullable=False),
    sa.Column('straight_hit_rate', sa.Float(), nullable=False),
    sa.Column('box_hit_rate', sa.Float(), nullable=False),
    sa.Column('avg_payout_per_play', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('run_duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_runs_strategy', ['strategy_name', 'game_type'], unique=False)
        batch_op.create_index('ix_backtest_runs_user', ['user_id'], unique=False)

    op.create_table('ensemble_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ensemble_weights', schema=None) as batch_op:
        batch_op.create_index('ix_ensemble_weights_game_strategy', ['game_type', 'strategy_name'], unique=False)
        batch_op.create_index('ix_ensemble_weights_user', ['user_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('target_draw_date', sa.DateTime(), nullable=False),
    sa.Column('target_draw_time', sa.String(length=10), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('digit_1', sa.Integer(), nullable=False),
    sa.Column('digit_2', sa.Integer(), nullable=False),
    sa.Column('digit_3', sa.Integer(), nullable=False),
    sa.Column('digit_4', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_play_type', sa.String(length=20), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('is_backtest', sa.Boolean(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('actual_draw_id', sa.Integer(), nullable=True),
    sa.Column('straight_hit', sa.Boolean(), nullable=True),
    sa.Column('box_hit', sa.Boolean(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actual_draw_id'], ['draws.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_predictions_backtest', ['is_backtest'], unique=False)
        batch_op.create_index('ix_predictions_strategy', ['strategy_name', 'game_type'], unique=False)
        batch_op.create_index('ix_predictions_target_lookup', ['game_type', 'target_draw_date', 'target_draw_time'], unique=False)
        batch_op.create_index('ix_predictions_user', ['user_id'], unique=False)

    op.create_table('backtest_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('predicted_digits', sqlite.JSON(), nullable=False),
    sa.Column('actual_digits', sqlite.JSON(), nullable=False),
    sa.Column('straight_hit', sa.Boolean(), nullable=False),
    sa.Column('box_hit', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_details', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_details_draw', ['draw_id'], unique=False)
        batch_op.create_index('ix_backtest_details_run', ['backtest_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_details', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_details_run')
        batch_op.drop_index('ix_backtest_details_draw')

    op.drop_table('backtest_details')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_predictions_user')
        batch_op.drop_index('ix_predictions_target_lookup')
        batch_op.drop_index('ix_predictions_strategy')
        batch_op.drop_index('ix_predictions_backtest')

    op.drop_table('predictions')
    with op.batch_alter_table('ensemble_weights', schema=None) as batch_op:
        batch_op.drop_index('ix_ensemble_weights_user')
        batch_op.drop_index('ix_ensemble_weights_game_strategy')

    op.drop_table('ensemble_weights')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_runs_user')
        batch_op.drop_index('ix_backtest_runs_strategy')

    op.drop_table('backtest_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stat_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_stat_snapshots_game_type')
        batch_op.drop_index('ix_stat_snapshots_date')

    op.drop_table('stat_snapshots')
    with op.batch_alter_table('model_performance', schema=None) as batch_op:
        batch_op.drop_index('ix_model_perf_window')
        batch_op.drop_index('ix_model_perf_strategy_game')

    op.drop_table('model_performance')
    with op.batch_alter_table('draws', schema=None) as batch_op:
        batch_op.drop_index('ix_draws_game_time')
        batch_op.drop_index('ix_draws_game_date_desc')

    op.drop_table('draws')
    # ### end Alembic commands ###
